package: community.lazycat.app.animehelper
version: 3.3.1
name: Anime Helper
description: "自动追番/下载工具，使用Docker部署，支持qBittorrent和Aria下载"
min_os_version: "1.5.0"
homepage: https://github.com/Zhoucheng133/Anime-Helper
author: Zhoucheng133
locales:
  zh:
    description: "自动追番/下载工具，使用Docker部署，支持qBittorrent和Aria下载"
    name: Anime Helper
  en:
    description: "Auto anime tracking/downloading tool, deployed with Docker, supporting qBittorrent and Aria download"
    name: Anime Helper
